apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-service
  namespace: garage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-service
  template:
    metadata:
      labels:
        app: cdc-service
    spec:
      containers:
        - name: cdc-service
          image: vinesen1/microservice-project-cdc-service
          ports:
            - containerPort: 8084
          env:
            - name: CLIENT_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cdc-secret 
                  key: CLIENT_DB_USERNAME
            - name: CLIENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cdc-secret
                  key: CLIENT_DB_PASSWORD
            - name: VEHICLE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cdc-secret
                  key: VEHICLE_DB_USERNAME
            - name: VEHICLE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cdc-secret
                  key: VEHICLE_DB_PASSWORD
            - name: MAINTENANCE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cdc-secret
                  key: MAINTENANCE_DB_USERNAME
            - name: MAINTENANCE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cdc-secret
                  key: MAINTENANCE_DB_PASSWORD
            
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
