apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-config
  namespace: garage-ns
data:
  MONGO_URI: "mongodb://admin:cGFzc3dvcmQ=@mongodb:27017/invoice_db?authSource=admin"
  MONGO_DATABASE: "invoice_db"
  MONGO_USERNAME: admin
