apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: garage-ns
spec:
  hosts:
    - "garage-gateway" # Adjusted to match the service name
  http:
    - route:
        - destination:
            host: frontend
            subset: v1
          weight: 0
        - destination:
            host: frontend
            subset: v2
          weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
  namespace: garage-ns
spec:
  host: frontend # Adjusted to match the service name
  subsets:
    - name: v1
      labels:
        version: v1
        app: frontend
    - name: v2
      labels:
        version: v2
        app: frontend
