apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: garage-gateway
  namespace: garage-ns
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: custom-gateway
spec:
  hosts:
    - "*"
  gateways:
    - garage-gateway
  http:
    - match:
        - uri:
            prefix: /ui
      route:
        - destination:
            host: frontend
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: gateway-service
            port:
              number: 8999
