apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-vehicule-service
  namespace: garage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-vehicule-service
  serviceName: "mysql-vehicule-service"
  template:
    metadata:
      labels:
        app: mysql-vehicule-service
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: vehicule-config
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: vehicule-config
                  key: MYSQL_DATABASE_VEHICULE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vehicule-secret
                  key: MYSQL_PASSWORD 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vehicule-secret
                  key: MYSQL_PASSWORD 
          volumeMounts:
            - name: mysql-vehicule-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-vehicule-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-vehicule-service
  namespace: garage-ns
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
  selector:
    app: mysql-vehicule-service
