apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: custom-gateway
spec:
  hosts:
    - "*"
  gateways:
    - garage-gateway 
  http:
    - match:
        - uri:
            prefix: "/ui"  
      route:
        - destination:
            host: client-service 
            port:
              number: 8080 
    - match:
        - uri:
            prefix: "/"  
      route:
        - destination:
            host: gateway-service 
            port:
              number: 8999 

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gateway-service-destination-rule
spec:
  host: gateway-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1 
      http:
        http1MaxPendingRequests: 1 
        maxRequestsPerConnection: 1 
    outlierDetection:
      consecutiveErrors: 1 
      interval: 1s 
      baseEjectionTime: 3m 
      maxEjectionPercent: 100 