apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2-deployment
  namespace: garage-ns
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
        version: v2
    spec:
      containers:
        - name: frontend
          image: vinesen1/frontend2
          ports:
            - containerPort: 80
