apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: garage-ns
  labels:
    name: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    name: http-frontend
  selector:
    name: frontend
